Update github-actions-htmlextra-report.yml

diff --git a/.github/workflows/github-actions-htmlextra-report.yml b/.github/workflows/github-actions-htmlextra-report.yml
--- a/.github/workflows/github-actions-htmlextra-report.yml
+++ b/.github/workflows/github-actions-htmlextra-report.yml
@@ -29,7 +29,7 @@ jobs:
         
    # Run the POSTMAN collection
       - name: Run API Tests
-        run: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export testResults/htmlreport.html || rc=$?; echo $rc; failure=false
+        run: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export testResults/htmlreport.html || {rc=$?;if [[ $rc != 0 ]]; then echo $rc; echo "^ Return Code ^";echo "$file failed";failure=true;fi}
 
     # Upload the contents of Test Results directory to workspace
       - name: Output the run Details
